from django.contrib.gis.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    image_url = models.URLField(max_length=500, blank=True, null=True, help_text="Optional icon or image for the category")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    image_url = models.URLField(max_length=500, blank=True, null=True, help_text="Optional icon or image for the tag/vibe")
    is_vibe = models.BooleanField(default=False, help_text="True if generated by LLM, False if parsed from KudaGo")

    def __str__(self):
        return self.name

class Place(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    
    location = models.PointField(geography=True)
    
    kudago_id = models.IntegerField(unique=True, null=True, blank=True)
    
    is_active = models.BooleanField(default=True)
    is_analyzed = models.BooleanField(default=False, help_text="True if processed by LLM for vibes/icebreakers")
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="places")
    tags = models.ManyToManyField(Tag, blank=True, related_name="places")
    
    photos = models.JSONField(default=list, blank=True, help_text="List of photo URLs")
    icebreakers = models.JSONField(default=list, blank=True, help_text="List of LLM-generated icebreakers")

    opening_hours = models.JSONField(default=dict, blank=True, null=True, help_text="Structured opening hours JSON")
    opening_hours_text = models.CharField(max_length=500, blank=True, null=True, help_text="Raw opening hours string from KudaGo")
    price_level = models.IntegerField(
        default=1,
        choices=[
            (0, 'Free'),
            (1, 'Low'),
            (2, 'Medium'),
            (3, 'High')
        ],
        help_text="Price level: 0=Free, 1=Low, 2=Medium, 3=High"
    )
    is_indoor = models.BooleanField(default=False, help_text="True if the place is indoors, False if outdoors")

    def __str__(self):
        return self.title

