# Generated by Django 5.0.14 on 2026-04-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_vibe',
            field=models.BooleanField(default=False, help_text='True if generated by LLM, False if parsed from KudaGo'),
        ),
    ]
