# Generated by Django 5.0.14 on 2026-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_tag_is_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='icebreakers',
            field=models.JSONField(blank=True, default=list, help_text='List of LLM-generated icebreakers'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_analyzed',
            field=models.BooleanField(default=False, help_text='True if processed by LLM for vibes/icebreakers'),
        ),
    ]
