# Generated by Django 5.0.14 on 2026-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_icebreakers_place_is_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_indoor',
            field=models.BooleanField(default=False, help_text='True if the place is indoors, False if outdoors'),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Structured opening hours JSON', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours_text',
            field=models.CharField(blank=True, help_text='Raw opening hours string from KudaGo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='price_level',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Price level: 0=Free, 1=Low, 2=Medium, 3=High'),
        ),
    ]
